global
        log /dev/log local0 
        chroot /var/lib/haproxy
        user haproxy
        group haproxy
        daemon
        maxconn 4000

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        option redispatch
        retries 3
        timeout client 35s
        timeout server 60s
        timeout connect 5s
        timeout http-keep-alive 10s
#        contimeout 5000
#        clitimeout 50000
#        srvtimeout 50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

listen stats
        bind *:9090
        balance
        mode http
        stats enable
	stats uri /
	stats auth admin:admin

frontend master-https       
        bind 10.120.248.10:443
        mode tcp
	option socket-stats
	tcp-request inspect-delay 5s
        tcp-request content accept if ( req_ssl_hello_type 1 )
        default_backend k8s-masters
		
backend k8s-masters
        stats enable
	mode tcp
        stick-table type binary len 32 30k expire 30m
        acl clienthello req_ssl_hello_type 1
	acl serverhello req_ssl_hello_type 2
        tcp-request inspect-delay 5s
        tcp-request content accept if clienthello
	tcp-repsonse content accept if serverhello
	stick on payload_lv(43,1) if clienthello
	stick store-response payload_lv(43,1) if serverhello
	option ssl-hello-chk
        server master01 10.120.248.14:443 check
        server master02 10.120.248.15:443 check
